#INCLUDE <16F887.H>
#DEVICE ADC=10 
#USE DELAY(CLOCK=4000000)
#FUSES INTRC_IO,NOWDT,NOPUT,NOMCLR,NOPROTECT,NOCPD,NOBROWNOUT
#FUSES NOIESO,NOFCMEN,NOLVP,NODEBUG,NOWRT,BORV21

#USE FAST_IO(A)
#USE FAST_IO(B)
#USE FAST_IO(C)
#USE FAST_IO(D)

#INCLUDE <LCD1.C>
LONG D;
FLOAT V,K;

VOID MAIN ()
{
SET_TRIS_A(0XFF);
LCD_INIT();
SETUP_ADC(ADC_CLOCK_INTERNAL);
SETUP_ADC_PORTS(sAN0|sAN1|sAN2|sAN3);
SET_ADC_CHANNEL(0);   

   WHILE (TRUE)
   {
   D=READ_ADC();
   K=0.0048876;
   V=D*K;
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC, "DIGITAL = %Lu     \nANALOGICO = %1.3g      ",D,V);
   }
}
